export const categories: string[] = [
  'Kohaku',
  'Sanke',
  'Goromo',
  'Kawarimono',
  'Showasansoku',
  'Ogon',
  'Shiro Bekko',
  'Hikarimoyomono',
  'Utsurimono',
  'Hikari Utsurimono',
  'Asagi',
  'Kinginrin',
  'Shusui',
  'Tancho',
  'Shiro Utsuri',
  'Ki Utsuri',
  'Kumpay Slayer',
  'Matsuba',
  'Ogon Platinum',
  'Ogon Yamabuki',
  'Kujaku',
  'Hariwake',
  'Khikusui',
  'Kumonryu',
  'Ki Bekko',
  'Aka Bekko',
  'Shusui Asagi',
  'Tancho Goromo',
  'Tancho Goshiki',
  'Tancho Kohaku',
  'Tancho Kujaku',
  'Tancho Sanke',
  'Nezu Ogon',
  'Ai Goromo',
  'Orenji Ogon',
  'Budo Goromo',
  'Sumi Goromo',
  'Goshiki Goromo',
  'Kin Showa',
  'Yamato Nishiki',
  'Doitsu Hariwake',
  'Kikusui',
  'Ochiba Sigure',
  'Beni Kumonryu',
  'Benigoi',
  'Haijiro',
  'Aka Haijiro',
  'Chagoi',
  'Kigoi',
  'Midorigoi',
  'Soragoi',
  'Tancho Showa',
  'Nagashima',
  'Shusui Yamaju',
  'Lainnya'
]
